config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/users/confirm_email/:id', to: 'users#confirm_email', as: 'confirm_email_user'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/wishlist_types/create'
    get '/wishlist_types/new'
    get '/wishlist_types/destroy'
    root 'sessions#new', as: 'home'

    # resource :friendship, only: %i[destroy]
    delete '/friendship/:id', to: 'friendships#destroy'

    resources :friendships
    get '/friendships/show'
    post '/friendships/in', to: 'friendships#in'
    post '/friendships/out', to: 'friendships#out'

    post '/friendships/:id', to: 'friendships#accept'

    get '/users/new', to: 'users#new'
    get '/users/info_about_user', as: 'info_user'
    post '/users/edit', to: 'users#edit'
    post '/users/update'
    get '/users/edit', to: 'users#edit'
    get '/users/show', to: 'users#show'
    post '/users/show_by_login'
    get '/users/:id', to: 'friendships#create'
    get '/users/destroy'

    get '/gifts/set_giver/:id', to: 'gifts#set_giver', as: 'giver'
    get '/gifts/remove_giver/:id', to: 'gifts#remove_giver', as: 'remove_giver'
    get '/gifts/show/:id', to: 'gifts#show', as: 'wishlist'
    post '/gifts/show/:id', to: 'gifts#show_with_type', as: 'wishlist_with_type'
    get '/gifts/giver_presents'
    post '/gifts/create'
    resources :gifts

    get 'password/index', to: 'passwords#index'
    get 'password/new_password', to: 'passwords#new_password'
    post 'password/forgot', to: 'passwords#forgot'
    post 'password/reset', to: 'passwords#reset'
    put 'password/update', to: 'passwords#update'

    # resource :user, only: %i[destroy]

    get '/wishlist_types/show', to: 'wishlist_types#show'
    post '/wishlist_types/create', to: 'wishlist_types#create'

    resources :wishlist_types
    resource :wishlist_type, only: %i[destroy]
    resources :users
    # resource :gift, only: %i[destroy]
    resource :password, only: %i[update]
    resource :session, only: %i[new create destroy]
    resources :users do
      member do
        get :confirm_email
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# class of model
class User < ApplicationRecord
  include FriendshipsHelper
  has_secure_password

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :gifts, dependent: :destroy
  has_many :givers, through: :gifts

  before_create :confirmation_token

  validates :login, presence: true, uniqueness: true
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :login, presence: true, uniqueness: true
  validates :f_name, presence: true, format: { with: /\A[a-zа-яА-ЯA-Z]+\z/ }
  validates :l_name, presence: true, format: { with: /\A[a-zа-яА-ЯA-Z]+\z/ }
  validates :password_confirmation, presence: true
  validates :password, confirmation: true
  validates :password,
            format: { with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{8,}\z/,
                      message: I18n.t('activerecord.attributes.user.msg_error') }
  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
  end

  def generate_password_token!
    self.reset_password_token = generate_token
    save!(validate: false)
  end

  def reset_password!(password, password_confirmtion)
    self.reset_password_token = nil
    self.password = password
    self.password_confirmation = password_confirmtion
    save
  end

  private

  def generate_token
    SecureRandom.hex(10)
  end

  def confirmation_token
    self.confirm_token = SecureRandom.urlsafe_base64.to_s if confirm_token.blank?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# controller
class UsersController < ApplicationController
  include UsersHelper
  before_action :autorize, only: %i[edit info_about_user show_by_login]
  # before_action :set_user, only: %i[destroy]

  def new; end

  def edit; end

  def info_about_user; end

  # rubocop:disable Metrics/AbcSize
  def create
    @user = User.new(user_params)
    if !@user.save
      flash[:warning] = @user.errors.full_messages.join('. ')
      redirect_to new_user_path
    else
      UserMailer.registration_confirmation(@user).deliver
      flash[:success] = t('.send_email')
      redirect_to home_path
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = t('welcome')
      session[:user_id] = user.id
      redirect_to wishlist_path(user.id)
    else
      flash[:error] = 'Извините. Пользователь с таким логином не найден'
      redirect_to new_user_path
    end
  end
  # rubocop:enable Metrics/AbcSize

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = t('.update_data')
    else
      flash[:notice] = @user.errors.full_messages.join('. ')
    end
    redirect_to info_user_path
  end

  def destroy
    redirect_to home_path, notice: t('.delete_acc') if User.destroy(current_user.id)
  end

  def show
    @users = User.all
  end

  def show_by_login
    @user = User.find_by login: params[:login]
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# helper
module UsersHelper
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:f_name, :l_name, :login, :birth, :email, :password, :password_confirmation)
  end

  def user_params_update
    params.require(:user).permit(:f_name, :l_name, :login, :birth, :email, :password, :password_confirmation)
  end
end

app/views/users/_edit.html.erb
<div id='edit' class='div-form'>
  <div class='div-form' id='edit-user-form'>
    <%= form_with scope: :user, class: 'my-form', url: users_update_path do |form| %>
      <div class = 'form-group'>
        <%= form.label :f_name, t('.name'), id: 'label_name' %>
        <%= form.text_field :f_name, class: 'form-control', id: 'name' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :l_name, t('.last_name'), id: 'label_l_name' %>
        <%= form.text_field :l_name, class: 'form-control', id: 'l_name' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :login, t('passwords.index.login'), id: 'label_log' %>
        <%= form.text_field :login, class: 'form-control', id: 'log' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :birth, t('.birth'), id: 'label_b' %>
        <%= form.text_field :birth, class: 'form-control', id: 'birth' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :pass, t('passwords.new_password.password'), id: 'label_pass' %>
        <%= form.password_field :password, class: 'form-control', id: 'pass' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :pass_c, t('passwords.new_password.rep_password'), id: 'label_pass_c' %>
        <%= form.password_field :password_confirmation, class: 'form-control', id: 'pass_c' %>
      </div>
      <div class = 'form-group'>
        <%= form.submit(t('.upd_data'), id: 'update_btn',  class: 'btn btn-outline-dark') %>
      </div>
    <% end %>
  </div>

app/views/users/_edit_form.html.erb
  <div class='div-form' id='edit-user-form'>
    <%= form_with scope: :user, url: update_path, class: 'my-form', data: {turbo: false} do |form| %>
      <div class = 'form-group'>
        <%= form.label :f_name, 'Имя', id: 'label_name' %>
        <%= form.text_field :f_name, class: 'form-control', id: 'name' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :l_name, 'Фамилия', id: 'label_l_name' %>
        <%= form.text_field :l_name, class: 'form-control', id: 'l_name' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :login, 'Логин', id: 'label_log' %>
        <%= form.text_field :login, class: 'form-control', id: 'log' %>
      </div>
      <div class = 'form-group'>
        <%= form.label :birth, 'День рождения', id: 'label_b' %>
        <%= form.text_field :birth, class: 'form-control', id: 'birth' %>
      </div>
      <div class = 'form-group'>
        <%= form.submit('Изменить данные', id: 'update_btn',  class: 'btn btn-outline-dark') %>
      </div>
    <% end %>
  </div>

app/views/users/_show_by_login.html.erb
<div id='user-login'>
  <% if @user.nil? %>
    <h5 id='res'> <%= t('.err_find') %> </h5>
  <% else %>
    <div class='card cartocka' style='width: 25em;margin: 5px;'>
    <div class="card-body">
      <h5 class="card-title"> <%= @user.login %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= @user.f_name %> <%= @user.l_name %></h6>
      <p class="card-text"><%= @user.birth %></p>
      <% unless current_user.id == @user.id %>
        <% if !friends?(current_user.id, @user.id) && !request_present?(current_user.id, @user.id) %>
          <%= link_to t('.add_to_friends'), user, class: 'card-link text-dark'%>
        <% elsif friends?(current_user.id, @user.id) %>
          <p class="card-text"> <%= t('.already_friends') %></p>
        <% end %>
        <% else %>
          <p class="card-text"> <%= t('.me') %></p>
        <% end %>    
        </div>
  </div>
  <% end %>
  <%= link_to t('.return'), users_show_path, class: 'card-link text-dark'%>
</div>

app/views/users/edit.turbo_stream.erb
<%= turbo_stream.update 'container-info', partial: 'edit'%>

app/views/users/info_about_user.html.erb
<div id='div-info' class='div-form'>
  <div id='container-info'>
    <ul>
      <li> <%= t('users.edit.name')%> <%= current_user.f_name %></li>
      <li> <%= t('users.edit.last_name') %> <%= current_user.l_name %></li>
      <li> <%= t('passwords.index.login') %> <%= current_user.login %></li>
      <li> <%= t('.email')%> <%=  current_user.email %></li>
      <li> <%= t('users.edit.birth')%> <%=  current_user.birth %></li>
      <li> <%= t('.date_reg')%> <%=  current_user.created_at %></li>
    </ul>
  </div>
  <div class='links'>
    <ul>
      <li><%= link_to t('.edit_data'), users_edit_path, class: 'text-dark', data: {turbo_method: :post}, id: 'edit_link' %></li>
      <li><%= link_to t('.return'), wishlist_path(current_user.id), id: 'to_wishlist', class: 'text-dark' %></li>
      <li><%= button_to t('.del'), users_destroy_path, method: :delete, id: 'delete_p', class: 'btn btn-outline-danger' %></li>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class='div-form animation-div'>
  <%= form_with scope: :user, url: users_path, class: 'my-form', data: {turbo: false} do |form| %>
    <div class = 'form-group'>
      <%= form.label :f_name, t('users.edit.name'), id: 'label_name' %>
      <%= form.text_field :f_name, class: 'form-control', id: 'name' %>
    </div>
    <div class = 'form-group'>
      <%= form.label :l_name, t('users.edit.last_name'), id: 'label_l_name' %>
      <%= form.text_field :l_name, class: 'form-control', id: 'l_name' %>
    </div>
    <div class = 'form-group'>
      <%= form.label :email, t('users.info_about_user.email'), id: 'label_em' %>
      <%= form.text_field :email, class: 'form-control', id: 'email' %>
      <small id="emailHelp" class="form-text text-muted"><%= t('.tell') %></small>
    </div>
    <div class = 'form-group'>
      <%= form.label :login, t('passwords.index.login'), id: 'label_log' %>
      <%= form.text_field :login, class: 'form-control', id: 'log' %>
    </div>
    <div class = 'form-group'>
      <%= form.label :pass, t('passwords.new_password.password'), id: 'label_pass' %>
      <%= form.password_field :password, class: 'form-control', id: 'pass' %>
    </div>
        <div class = 'form-group'>
      <%= form.label :pass_c, t('passwords.new_password.rep_password'), id: 'label_pass_c' %>
      <%= form.password_field :password_confirmation, class: 'form-control', id: 'pass_c' %>
    </div>
    <div class = 'form-group'>
      <%= link_to t('.have_acc'), home_path, class: 'link-dark'%>
      <%= form.submit(t('.reg'), id: 'reg_btn',  class: 'btn btn-outline-dark') %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div id='show-users'>
  <div class=' users' id='user'>
    <% @users.each do |user| %>
        <div class='card cartocka' style='width: 25em;margin: 5px;'>
          <div class="card-body">
            <h5 class="card-title"> <%= user.login %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= user.f_name %> <%= user.l_name %></h6>
            <p class="card-text"> <%= user.birth %></p>
            <%unless user.email_confirmed then%> 
              <p class="card-text" style='color:red;'><%= t('.acc') %></p> 
            <% end %>
            <% if current_user.id != user.id %>
              <% if !friends?(current_user.id, user.id) && !request_present?(current_user.id, user.id) %>
                <%= link_to t('users.show_by_login.add_to_friends'), user, class: 'card-link text-dark'%>
              <% elsif friends?(current_user.id, user.id) %>
                <p class="card-text"> <%= t('users.show_by_login.already_friends')%> </p>
              <% end %>
            <% else %>
              <p class="card-text"> <%= t('users.show_by_login.me')%></p>
            <% end %>
          </div>
        </div>
    <%end%>
  </div>
  <div id='search-line'>
    <%= form_with url: users_show_by_login_path, class: 'my-form' do |form| %>
    <div class = 'form-group'>
      <%= form.label :login, t('passwords.index.login'), id: 'label_name' %>
      <%= form.text_field :login, class: 'form-control', id: 'login' %>
    </div>
    <% end %>
  </div>
    
</div>

app/views/users/show_by_login.turbo_stream.erb
<%= turbo_stream.update 'user', partial: 'show_by_login'%>