config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/users/confirm_email/:id', to: 'users#confirm_email', as: 'confirm_email_user'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/wishlist_types/create'
    get '/wishlist_types/new'
    get '/wishlist_types/destroy'
    root 'sessions#new', as: 'home'

    # resource :friendship, only: %i[destroy]
    delete '/friendship/:id', to: 'friendships#destroy'

    resources :friendships
    get '/friendships/show'
    post '/friendships/in', to: 'friendships#in'
    post '/friendships/out', to: 'friendships#out'

    post '/friendships/:id', to: 'friendships#accept'

    get '/users/new', to: 'users#new'
    get '/users/info_about_user', as: 'info_user'
    post '/users/edit', to: 'users#edit'
    post '/users/update'
    get '/users/edit', to: 'users#edit'
    get '/users/show', to: 'users#show'
    post '/users/show_by_login'
    get '/users/:id', to: 'friendships#create'
    get '/users/destroy'

    get '/gifts/set_giver/:id', to: 'gifts#set_giver', as: 'giver'
    get '/gifts/remove_giver/:id', to: 'gifts#remove_giver', as: 'remove_giver'
    get '/gifts/show/:id', to: 'gifts#show', as: 'wishlist'
    post '/gifts/show/:id', to: 'gifts#show_with_type', as: 'wishlist_with_type'
    get '/gifts/giver_presents'
    post '/gifts/create'
    resources :gifts

    get 'password/index', to: 'passwords#index'
    get 'password/new_password', to: 'passwords#new_password'
    post 'password/forgot', to: 'passwords#forgot'
    post 'password/reset', to: 'passwords#reset'
    put 'password/update', to: 'passwords#update'

    # resource :user, only: %i[destroy]

    get '/wishlist_types/show', to: 'wishlist_types#show'
    post '/wishlist_types/create', to: 'wishlist_types#create'

    resources :wishlist_types
    resource :wishlist_type, only: %i[destroy]
    resources :users
    # resource :gift, only: %i[destroy]
    resource :password, only: %i[update]
    resource :session, only: %i[new create destroy]
    resources :users do
      member do
        get :confirm_email
      end
    end
  end
end

app/models/gift.rb
# frozen_string_literal: true

# class of model
class Gift < ApplicationRecord
  belongs_to :user
  belongs_to :wishlist_type
  # belongs_to :giver, class_name: 'User'

  validates :user_id, :name, :link, presence: true
end

app/controllers/gifts_controller.rb
# frozen_string_literal: true

# controller
class GiftsController < ApplicationController
  before_action :set_gift, only: %i[destroy]
  before_action :set_user, only: %i[show show_with_type]
  before_action :autorize
  include GiftsHelper

  def new; end

  def show
    @gifts = Gift.where user_id: @user.id
  end

  def show_with_type
    @gifts = Gift.where user_id: @user.id, wishlist_type_id: params[:id_type]
  end

  def create
    @gift = Gift.new(gift_params)
    redirect_to wishlist_path(current_user.id)
    flash[:notice] = @gift.errors.full_messages.join(' и ') unless @gift.save
  end

  def set_giver
    @gift = Gift.find(params[:id])
    @gift.update(giver_id: current_user.id)
    redirect_to wishlist_path(@gift.user_id.to_s)
  end

  def remove_giver
    @gift = Gift.find(params[:id])
    @gift.update(giver_id: nil)
    redirect_to wishlist_path(@gift.user_id.to_s)
  end

  def giver_presents
    @gifts = Gift.where(giver_id: current_user.id)
  end

  def destroy
    @gift.destroy
    @gifts = Gift.where user_id: @gift.user_id
  end
end

app/helpers/gifts_helper.rb
# frozen_string_literal: true

# helper
module GiftsHelper
  def gift_params
    params.require(:gift).permit(:name, :link, :description, :user_id, :giver_id, :wishlist_type_id)
  end

  def set_gift
    @gift = Gift.find(params[:id])
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/gifts/_destroy.html.erb
<% @gifts.each do |gift| %>
          <div class='card cartocka' style='width: 25em;margin: 5px;' id='container_<%= gift.id%>' onmouseover=change_color(id) onmouseout=change_color_back(id)>
          <div class="card-body">
            <div  style='display:inline-block;  vertical-align: middle;'>
              <h5 class="card-title"> <%= gift.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= t('.type_wishlist') %> <%= WishlistType.find(gift.wishlist_type_id).name %></h6>
              <h6 class="card-subtitle mb-2 text-muted"><%= gift.description %></h6>
              <%= link_to t('.link_gift'), gift.link, class: 'card-link text-dark'%>
            </div>
            <div  style= 'display:inline-block;  vertical-align: middle;margin-left: 50%;' >
            <%= button_to gift, method: :delete, class: 'btn btn-danger btn-circle btn-sm' do %>
                <%= image_tag 'icons8-trash-can.svg', style: 'width:40px;height:40px;' %>
            <% end%>
            </div>
          </div>
        </div>
<%end%>

app/views/gifts/_show_with_type.html.erb
 <% if @gifts.empty? %>
            <%= image_tag 'empty.png', id: 'empty-icon'%>
    <% else %>
      <% @gifts.each do |gift| %>
          <div class='card cartocka' style='width: 25em;margin: 5px;' id='container_<%= gift.id%>' onmouseover=change_color(id) onmouseout=change_color_back(id)>
            <div class="card-body">
              <div  style='display:inline-block;  vertical-align: middle;width:70%;'>
                <h5 class="card-title"> <%= gift.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= gift.description %></h6>
                <%= link_to t('gifts.destroy.link_gift'), gift.link, class: 'card-link text-dark'%>
              </div>
              <div  style= 'display:inline-block;  vertical-align: middle;' >
                <% if gift.user_id == current_user.id %>
                  <%= button_to gift, method: :delete, class: 'btn btn-danger btn-circle btn-sm' do %>
                      <%= image_tag 'icons8-trash-can.svg', style: 'width:40px;height:40px;' %>
                  <% end%>
                <% elsif gift.giver_id.nil? %>
                  <%= button_to t('application.i_give'), giver_path(gift.id), method: :get, class: 'btn btn-success btn-circle' %>
                <% elsif gift.giver_id == current_user.id %>
                  <%= button_to t('application.i_d_give'), remove_giver_path(gift.id), method: :get, class: 'btn btn-danger btn-circle' %>
                <% else %>
                  <p><%= t('.taken') %></p>
                <% end %>
              </div>
            </div>
          </div>
    <%end%>
    <% end %>

app/views/gifts/destroy.turbo_stream.erb
<%= turbo_stream.update 'gifts', partial: 'destroy'%>

app/views/gifts/giver_presents.html.erb
  <div id='gifts'>
    <% if @gifts.empty? %>
            <%= image_tag 'empty.png', id: 'empty-icon'%>
    <% else %>
      <% @gifts.each do |gift| %>
          <div class='card cartocka' style='width: 25em;margin: 5px;'>
            <div class="card-body">
              <div  style='display:inline-block;  vertical-align: middle;width:70%;'>
                <h5 class="card-title"> <%= gift.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= gift.description %></h6>
                <h6 class="card-subtitle mb-2 text-muted"><%=link_to User.find(gift.user_id).login, wishlist_path(gift.user_id), class: 'card-link text-dark'%></h6>
                <%= link_to t('gifts.destroy.link_gift'), gift.link, class: 'card-link text-dark'%>
              </div>
            </div>
          </div>
    <%end%>
    <% end %>
  </div>
</div>

app/views/gifts/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= form_with scope: :gift, class: 'my-form', url: '/gifts/create', data: {turbo: false}  do |form| %>
  <%# костыль ужас. убрать потом.... %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :giver_id %>
    <div class = 'form-group'>
      <%= form.label :name, t('gifts.destroy.type_wishlist')%>
      <%= form.select( :wishlist_type_id, options_from_collection_for_select(WishlistType.all, :id, :name), class: 'btn btn-success dropdown-toggle form-control' ) %>
    </div>
    <div class = 'form-group'>
      <%= form.label :name, t('.name') %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class = 'form-group'>
      <%= form.label :link, t('gifts.destroy..link_gift')%>
      <%= form.text_field :link, class: 'form-control' %>
    </div>
    <div class = 'form-group'>
      <%= form.label :desc, t('.label_desc')%>
      <%= form.text_field :description, class: 'form-control' %>
      <small id="emailHelp" class="form-text text-muted"><%= t('.desc')%></small>
    </div>
    <div class = 'form-group'>
      <%= link_to t('.close'), wishlist_path(current_user.id), class: 'link-dark'%>
      <%= form.submit t('.add'), id: 'add_btn',  class: 'btn btn-outline-dark', style: 'width: 50%;'%>
    </div>
  <% end %>
<% end %>

app/views/gifts/show.html.erb
<% if current_user.id == @user.id %>
  <%= link_to new_gift_path, data: { turbo_frame: 'modal' } do %>
    <%= image_tag 'add_gift.png', style: 'width:70px;height:70px;', class: 'add_gift_icon'%>
  <% end%>
<% end %>
<div>
<%= form_with class: 'my-form', id:'form-type',url: wishlist_with_type_path do |form| %>
    <div class = 'form-group' id='div-form-type'>
      <%= form.label :name, t('gifts.destroy.type_wishlist') %>
      <%= form.select( :id_type, options_from_collection_for_select(WishlistType.all, :id, :name), class: 'btn btn-success dropdown-toggle form-control' ) %>
      <%= form.submit t('.show'), id: 'add_btn',  class: 'btn btn-outline-dark', style: 'width: 50%;margin-left:25%;margin-top:5px;', data: {turbo_method: :post}%>
    </div>
<% end %>
  <div id='gifts'>
    <% if @gifts.empty? %>
            <%= image_tag 'empty.png', id: 'empty-icon'%>
    <% else %>
      <% @gifts.each do |gift| %>
          <div class='card cartocka' style='width: 25em;margin: 5px;' id='container_<%= gift.id%>' onmouseover=change_color(id) onmouseout=change_color_back(id)>
            <div class="card-body">
              <div  style='display:inline-block;  vertical-align: middle;width:70%;'>
                <h5 class="card-title"> <%= gift.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= gift.description %></h6>
                <h6 class="card-subtitle mb-2 text-muted"><%=t('gifts.destroy.type_wishlist') %><%= WishlistType.find(gift.wishlist_type_id).name %></h6>
                <%= link_to t('gifts.destroy.link_gift'), gift.link, class: 'card-link text-dark'%>
              </div>
              <div  style= 'display:inline-block;  vertical-align: middle;' >
                <% if gift.user_id == current_user.id %>
                  <%= button_to gift, method: :delete, class: 'btn btn-danger btn-circle btn-sm' do %>
                      <%= image_tag 'icons8-trash-can.svg', style: 'width:40px;height:40px;' %>
                  <% end%>
                <% elsif gift.giver_id.nil? %>
                  <%= button_to t('application.i_give'), giver_path(gift.id), method: :get, class: 'btn btn-success btn-circle' %>
                <% elsif gift.giver_id == current_user.id %>
                  <%= button_to t('application.i_d_give'), remove_giver_path(gift.id), method: :get, class: 'btn btn-danger btn-circle' %>
                <% else %>
                  <p> <%= t('gifts.show_with_type.taken')%> </p>
                <% end %>
              </div>
            </div>
          </div>
    <%end%>
    <% end %>
  </div>
</div>
  <script>
  function change_color(id) {
     document.getElementById(id).style.backgroundColor = '#E3EBFDEC';
  }

  function change_color_back(id) {
    document.getElementById(id).style.backgroundColor = '#E3F2FD';
  }
</script>

app/views/gifts/show_with_type.turbo_stream.erb
<%= turbo_stream.update 'gifts', partial: 'show_with_type'%>