config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/users/confirm_email/:id', to: 'users#confirm_email', as: 'confirm_email_user'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/wishlist_types/create'
    get '/wishlist_types/new'
    get '/wishlist_types/destroy'
    root 'sessions#new', as: 'home'

    # resource :friendship, only: %i[destroy]
    delete '/friendship/:id', to: 'friendships#destroy'

    resources :friendships
    get '/friendships/show'
    post '/friendships/in', to: 'friendships#in'
    post '/friendships/out', to: 'friendships#out'

    post '/friendships/:id', to: 'friendships#accept'

    get '/users/new', to: 'users#new'
    get '/users/info_about_user', as: 'info_user'
    post '/users/edit', to: 'users#edit'
    post '/users/update'
    get '/users/edit', to: 'users#edit'
    get '/users/show', to: 'users#show'
    post '/users/show_by_login'
    get '/users/:id', to: 'friendships#create'
    get '/users/destroy'

    get '/gifts/set_giver/:id', to: 'gifts#set_giver', as: 'giver'
    get '/gifts/remove_giver/:id', to: 'gifts#remove_giver', as: 'remove_giver'
    get '/gifts/show/:id', to: 'gifts#show', as: 'wishlist'
    post '/gifts/show/:id', to: 'gifts#show_with_type', as: 'wishlist_with_type'
    get '/gifts/giver_presents'
    post '/gifts/create'
    resources :gifts

    get 'password/index', to: 'passwords#index'
    get 'password/new_password', to: 'passwords#new_password'
    post 'password/forgot', to: 'passwords#forgot'
    post 'password/reset', to: 'passwords#reset'
    put 'password/update', to: 'passwords#update'

    # resource :user, only: %i[destroy]

    get '/wishlist_types/show', to: 'wishlist_types#show'
    post '/wishlist_types/create', to: 'wishlist_types#create'

    resources :wishlist_types
    resource :wishlist_type, only: %i[destroy]
    resources :users
    # resource :gift, only: %i[destroy]
    resource :password, only: %i[update]
    resource :session, only: %i[new create destroy]
    resources :users do
      member do
        get :confirm_email
      end
    end
  end
end

app/models/friendship.rb
# frozen_string_literal: true

# class of model
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user_id, presence: true
  validates :friend_id, presence: true
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

# class of controller
class FriendshipsController < ApplicationController
  include FriendshipsHelper
  before_action :set_friendship, only: %i[destroy]
  before_action :autorize

  # rubocop:disable Metrics/AbcSize
  def create
    @friendship = Friendship.new do |rec|
      rec.user_id = current_user.id
      rec.friend_id = params[:id]
    end
    if @friendship.save!
      redirect_to users_show_path, notice: t('.msg_request')
    else
      redirect_to users_show_path, notice: @friendship.errors.full_messages.split.join('. ')
    end
  end
  # rubocop:enable Metrics/AbcSize

  def destroy
    @friendship.delete
    redirect_to friendships_out_path
  end

  def accept
    @friendship = Friendship.new do |rec|
      rec.user_id = current_user.id
      rec.friend_id = params[:id]
    end
    if @friendship.save!
      redirect_to friendships_show_path
    else
      redirect_to friendships_show_path, notice: @friendship.errors.full_messages.split.join('. ')
    end
  end

  def in; end

  def out; end

  def delete_friendship; end
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

# helper
module FriendshipsHelper
  def friends?(user1, user2)
    !Friendship.where(user_id: user1,
                      friend_id: user2).empty? && !Friendship.where(user_id: user2,
                                                                    friend_id: user1).empty?
  end

  def request_present?(user1, user2)
    (!Friendship.where(user_id: user1,
                       friend_id: user2).empty? ^ !Friendship.where(user_id: user2,
                                                                    friend_id: user1).empty?)
  end

  def is_users_request?(user1, user2)
    !Friendship.where(user_id: user1, friend_id: user2).empty?
  end

  def id_friendship(user1, user2)
    Friendship.find_by(user_id: user1, friend_id: user2).id
  end

  def set_friendship
    @friendship = Friendship.find(params[:id])
  end
end

app/views/friendships/_in.html.erb
<h3 style='text-align:center;margin-bottom:20px;'><%= t('.in') %></h3>
<% User.all.select { |u| request_present?(u.id, current_user.id) && is_users_request?(u.id, current_user.id) }.each do |user| %>     <%# не забыть убрать этот хардкод %>
        <div class='card cartocka' style='width: 25em;margin: 5px;'>
          <div class="card-body">
            <h5 class="card-title"> <%= user.login %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= user.f_name %> <%= user.l_name %></h6>
            <div class='btn-group' style='text-align: center;'>
                 <%= button_to t('.accept'),friendship_path(user.id), class: 'btn btn-success btn-circle'%>
                <%= button_to t('.reject'), friendship_path(id_friendship(user.id, current_user.id)), method: :delete, class: 'btn btn-danger btn-circle ',  style: 'margin-left:8px;'%>
            </div>
          </div>
        </div>
    <%end%>

app/views/friendships/_out.html.erb
<h3 style='text-align:center;margin-bottom:20px;'><%= t('.out') %></h3>
<% User.all.select { |u| request_present?(u.id, current_user.id) && is_users_request?( current_user.id, u.id) }.each do |user| %>     <%# не забыть убрать этот хардкод %>
        <div class='card cartocka' style='width: 25em;margin: 5px;'>
          <div class="card-body">
            <h5 class="card-title"> <%= user.login %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= user.f_name %> <%= user.l_name %></h6>
            <%= button_to   t('.del_req') , friendship_path(id_friendship(current_user.id, user.id)), method: :delete,class: 'btn btn-danger btn-circle btn-sm'%>        
          </div>
        </div>
    <%end%>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/in.turbo_stream.erb
<%= turbo_stream.update 'friends', partial: 'in'%>

app/views/friendships/out.turbo_stream.erb
<%= turbo_stream.update 'friends', partial: 'out'%>

app/views/friendships/show.html.erb
<div id='div-info' class='div-form'>

    <div id='friends'>
                <h3 style='text-align:center;margin-bottom:20px;'><%= t('application.friends') %></h3>
        <% User.all.select { |u| friends? u.id, current_user.id }.each do |user| %>     <%# не забыть убрать этот хардкод %>
        <div class='card cartocka' style='width: 25em;margin: 5px;'>
          <div class="card-body">
            <h5 class="card-title"> <%= user.login %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= user.f_name %> <%= user.l_name %></h6>
            <p class="card-text"><%= user.birth %></p>
            <div class='btn-group' style='text-align: center;'>
                <%= button_to t('application.home'), wishlist_path(user), method: :get, class: 'btn btn-success btn-circle'%>
                <%= button_to t('.del_friend'), friendship_path(id_friendship(current_user.id, user.id)), method: :delete, class: 'btn btn-danger btn-circle ',  style: 'margin-left:8px;'%>
            </div>
          </div>
        </div>
    <%end%>
    </div>
    <div class='links-left'>
        <ul>
            <li><%= link_to t('application.friends'), friendships_show_path, class: 'text-dark', id: 'show_all' %></li>
            <li><%= link_to t('friendships.in.in'), friendships_in_path, class: 'text-dark', data: {turbo_method: :post}, id: 'in_link'%></li>
            <li><%= link_to t('friendships.out.out'), friendships_out_path, class: 'text-dark',  data: {turbo_method: :post}, id: 'out_link' %></li>
        </ul>
    </div>
</div>