config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/users/confirm_email/:id', to: 'users#confirm_email', as: 'confirm_email_user'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/wishlist_types/create'
    get '/wishlist_types/new'
    get '/wishlist_types/destroy'
    root 'sessions#new', as: 'home'

    # resource :friendship, only: %i[destroy]
    delete '/friendship/:id', to: 'friendships#destroy'

    resources :friendships
    get '/friendships/show'
    post '/friendships/in', to: 'friendships#in'
    post '/friendships/out', to: 'friendships#out'

    post '/friendships/:id', to: 'friendships#accept'

    get '/users/new', to: 'users#new'
    get '/users/info_about_user', as: 'info_user'
    post '/users/edit', to: 'users#edit'
    post '/users/update'
    get '/users/edit', to: 'users#edit'
    get '/users/show', to: 'users#show'
    post '/users/show_by_login'
    get '/users/:id', to: 'friendships#create'
    get '/users/destroy'

    get '/gifts/set_giver/:id', to: 'gifts#set_giver', as: 'giver'
    get '/gifts/remove_giver/:id', to: 'gifts#remove_giver', as: 'remove_giver'
    get '/gifts/show/:id', to: 'gifts#show', as: 'wishlist'
    post '/gifts/show/:id', to: 'gifts#show_with_type', as: 'wishlist_with_type'
    get '/gifts/giver_presents'
    post '/gifts/create'
    resources :gifts

    get 'password/index', to: 'passwords#index'
    get 'password/new_password', to: 'passwords#new_password'
    post 'password/forgot', to: 'passwords#forgot'
    post 'password/reset', to: 'passwords#reset'
    put 'password/update', to: 'passwords#update'

    # resource :user, only: %i[destroy]

    get '/wishlist_types/show', to: 'wishlist_types#show'
    post '/wishlist_types/create', to: 'wishlist_types#create'

    resources :wishlist_types
    resource :wishlist_type, only: %i[destroy]
    resources :users
    # resource :gift, only: %i[destroy]
    resource :password, only: %i[update]
    resource :session, only: %i[new create destroy]
    resources :users do
      member do
        get :confirm_email
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar-expand-md navbar navbar-light border border-left-0 border-right-0 rounded-bottom" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <% if user_signed_in? %>
            <%= link_to wishlist_path(current_user.id) do %>
              <%= image_tag 'gift_icon.svg', style: 'width:30px;height:30px;' %>
            <% end%>
            <%= link_to t('application.home'), wishlist_path(current_user.id), class: 'navbar-brand abs' %>               
          <% else %>
            <%= link_to home_path do %>
              <%= image_tag 'gift_icon.svg', style: 'width:30px;height:30px;' %>
            <% end%>
            <%= link_to t('application.home'), home_path, class: 'navbar-brand abs' %>               
          <% end %>
          <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="collapseNavbar">
            <ul class="navbar-nav ms-auto">
              <%if user_signed_in?%>
                <% if current_user.admin %>
                  <li class="nav-item">
                    <%= link_to t('application.manage'), wishlist_types_show_path, class: 'nav-link'%>               
                  </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to t('application.users'), users_show_path, class: 'nav-link', id: 'all_users'%>               
                </li>
                <li class="nav-item">
                  <%= link_to t('application.friends'), friendships_show_path, class: 'nav-link', id: 'friends_link' %>               
                </li>
                <li class="nav-item">
                  <%= link_to t('application.i_give'), gifts_giver_presents_path, class: 'nav-link', id: 'i_give'%>               
                </li>
                <li class="nav-item">
                  <%= link_to t('application.account'), info_user_path, class: 'nav-link', id: 'account'%>               
                </li>
                <li class="nav-item">
                  <%= button_to t('application.exit'), session_path, method: :delete, class: 'btn btn-outline-dark', id: 'exit'%>               
                </li>
              <%end%>
              <li  class="nav-item">
                <% if I18n.locale == :ru %>
                  <%= link_to "RU", { locale: 'en' }, class: "local nav-link" %>
                <% else %>
                  <%= link_to "ENG", { locale: 'ru' } , class: "local nav-link"%>
                <%end%>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="content">
        <% flash.each do |type, msg| %>
          <div class='alert alert-info' id='flash'>
            <%= msg %>
          </div>
          <% flash.clear %>
        <% end %>
    <%= turbo_frame_tag "modal" %>
    <%= yield %>
    </div>

    <footer class="bg-light bd-footer text-center border border-left-0 border-right-0 rounded-top">
      <div class="text-center p-3" style="background-color: #e3f2fd;">
        <%=t('application.footer')%>
        <a class="text-dark" href='https://github.com/sp20ks'>Sp20ks</a>
      </div>
    </footer>
  </body>
</html>